backend:
  name: git-gateway
  branch: site

publish_mode: editorial_workflow

media_folder: "files"

display_url: https://ccsource.org

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "story"
    label: "Story"
    folder: "_posts"
    extension: "md"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - label: "tags"
        name: "tags"
        widget: "list"
        allow_add: true
        default: ["story"]
      - {label: "excerpt", name: "excerpt", widget: "string", required: false}
      - {label: "comments", name: "comments", widget: "hidden", default: true}
      - label: "date"
        name: "date"
        widget: "date"
        default: ""
        format: "MMM Do YY"
      - {label: "Body", name: "body", widget: "markdown", required: true}